/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cad12)
#  Generated on:      Wed Nov 27 12:51:35 2024
#  Design:            controller1
#  Command:           saveNetlist controller1_net_postRouting.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Nov 27 2024 12:34:25 IST (Nov 27 2024 07:04:25 UTC)
// Verification Directory fv/controller1 
module controller1 (
	clk, 
	rst, 
	status, 
	dataout);
   input clk;
   input rst;
   output status;
   output [7:0] dataout;

   // Internal wires
   wire [3:0] CA;
   wire [7:0] datain;
   wire [7:0] orig;
   wire [3:0] nextstate;
   wire [3:0] state;
   wire [4:0] count;
   wire [2:0] element_operation;
   wire Test;
   wire UNCONNECTED;
   wire element_done;
   wire fresh_state;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_134;
   wire re;
   wire we;

   assign state[3] = 1'b0 ;
   assign state[2] = 1'b0 ;
   assign fresh_state = 1'b1 ;
   assign element_operation[1] = 1'b0 ;
   assign element_operation[0] = 1'b0 ;
   assign element_operation[2] = 1'b0 ;
   assign count[1] = 1'b0 ;
   assign count[0] = 1'b0 ;
   assign count[2] = 1'b0 ;
   assign count[3] = 1'b0 ;
   assign count[4] = 1'b0 ;
   assign state[0] = 1'b0 ;
   assign state[1] = 1'b0 ;
   assign orig[4] = 1'b0 ;
   assign orig[7] = 1'b0 ;
   assign orig[6] = 1'b0 ;
   assign orig[5] = 1'b0 ;
   assign orig[0] = 1'b0 ;
   assign orig[3] = 1'b0 ;
   assign orig[2] = 1'b0 ;
   assign orig[1] = 1'b0 ;
   assign status = 1'b0 ;

   memory u (.clk(clk),
	.rst(rst),
	.CA(CA),
	.we(we),
	.datain({ datain[0],
		datain[0],
		datain[0],
		datain[0],
		datain[0],
		datain[0],
		datain[0],
		datain[0] }),
	.re(re),
	.dataout(dataout));
   TLATXL status_reg168 (.D(n_108),
	.G(n_109),
	.Q(status),
	.QN(UNCONNECTED));
   OAI31XL g3692__2398 (.A0(n_98),
	.A1(n_97),
	.A2(n_104),
	.B0(n_107),
	.Y(n_109));
   INVX1 g3693 (.A(n_107),
	.Y(n_108));
   OAI21XL g3694__5107 (.A0(orig[1]),
	.A1(n_105),
	.B0(n_106),
	.Y(n_107));
   NAND4XL g3695__6260 (.A(n_103),
	.B(orig[2]),
	.C(orig[3]),
	.D(orig[0]),
	.Y(n_106));
   OR4X1 g3696__4319 (.A(n_101),
	.B(orig[5]),
	.C(orig[6]),
	.D(orig[7]),
	.Y(n_105));
   NAND4XL g3697__8428 (.A(n_92),
	.B(n_99),
	.C(n_96),
	.D(n_102),
	.Y(n_104));
   NOR2BXL g3698__5526 (.AN(orig[5]),
	.B(n_100),
	.Y(n_103));
   NOR3XL g3699__6783 (.A(n_93),
	.B(n_94),
	.C(n_95),
	.Y(n_102));
   OR4X1 g3700__3680 (.A(orig[0]),
	.B(orig[2]),
	.C(orig[3]),
	.D(orig[4]),
	.Y(n_101));
   NAND4XL g3701__1617 (.A(orig[1]),
	.B(orig[4]),
	.C(orig[7]),
	.D(orig[6]),
	.Y(n_100));
   XNOR2X1 g3702__2802 (.A(orig[2]),
	.B(dataout[2]),
	.Y(n_99));
   AOI21XL g3703__1705 (.A0(orig[3]),
	.A1(dataout[3]),
	.B0(n_91),
	.Y(n_98));
   AOI21XL g3704__5122 (.A0(orig[7]),
	.A1(dataout[7]),
	.B0(n_90),
	.Y(n_97));
   XNOR2X1 g3705__8246 (.A(orig[0]),
	.B(dataout[0]),
	.Y(n_96));
   CLKXOR2X1 g3706__7098 (.A(orig[4]),
	.B(dataout[4]),
	.Y(n_95));
   CLKXOR2X1 g3707__6131 (.A(orig[5]),
	.B(dataout[5]),
	.Y(n_94));
   CLKXOR2X1 g3708__1881 (.A(orig[6]),
	.B(dataout[6]),
	.Y(n_93));
   XNOR2X1 g3709__5115 (.A(orig[1]),
	.B(dataout[1]),
	.Y(n_92));
   NOR2XL g3710__7482 (.A(orig[3]),
	.B(dataout[3]),
	.Y(n_91));
   NOR2BXL g3711__4733 (.AN(nextstate[1]),
	.B(rst),
	.Y(state[1]));
   NOR2XL g3712__6161 (.A(orig[7]),
	.B(dataout[7]),
	.Y(n_90));
   NOR2BXL g3713__9315 (.AN(nextstate[0]),
	.B(rst),
	.Y(state[0]));
   SDFFRHQX1 \count_reg[4]  (.CK(clk),
	.D(n_88),
	.Q(count[4]),
	.RN(n_5),
	.SE(n_71),
	.SI(count[4]));
   DFFRHQX1 \count_reg[3]  (.CK(clk),
	.D(n_89),
	.Q(count[3]),
	.RN(n_5));
   SDFFQXL \CA_reg[3]  (.CK(clk),
	.D(CA[3]),
	.Q(CA[3]),
	.SE(n_75),
	.SI(n_82));
   SDFFQXL \CA_reg[1]  (.CK(clk),
	.D(CA[1]),
	.Q(CA[1]),
	.SE(n_75),
	.SI(n_60));
   SDFFQXL \CA_reg[2]  (.CK(clk),
	.D(CA[2]),
	.Q(CA[2]),
	.SE(n_75),
	.SI(n_73));
   OAI2BB1XL g4153__9945 (.A0N(n_71),
	.A1N(count[3]),
	.B0(n_86),
	.Y(n_89));
   OAI21XL g4154__2883 (.A0(count[4]),
	.A1(n_72),
	.B0(n_87),
	.Y(n_88));
   SDFFQXL \CA_reg[0]  (.CK(clk),
	.D(CA[0]),
	.Q(CA[0]),
	.SE(n_75),
	.SI(n_42));
   DFFQX1 \orig_reg[1]  (.CK(clk),
	.D(n_83),
	.Q(orig[1]));
   DFFQX1 \orig_reg[4]  (.CK(clk),
	.D(n_79),
	.Q(orig[4]));
   DFFQX1 \orig_reg[3]  (.CK(clk),
	.D(n_81),
	.Q(orig[3]));
   DFFQX1 \orig_reg[0]  (.CK(clk),
	.D(n_84),
	.Q(orig[0]));
   DFFQX1 \orig_reg[2]  (.CK(clk),
	.D(n_76),
	.Q(orig[2]));
   SDFFRHQX1 \count_reg[2]  (.CK(clk),
	.D(n_51),
	.Q(count[2]),
	.RN(n_5),
	.SE(n_71),
	.SI(count[2]));
   SDFFRHQX1 \count_reg[0]  (.CK(clk),
	.D(n_8),
	.Q(count[0]),
	.RN(n_5),
	.SE(n_71),
	.SI(count[0]));
   DFFRHQX1 \count_reg[1]  (.CK(clk),
	.D(n_85),
	.Q(count[1]),
	.RN(n_5));
   DFFQX1 \orig_reg[5]  (.CK(clk),
	.D(n_80),
	.Q(orig[5]));
   DFFQX1 \orig_reg[7]  (.CK(clk),
	.D(n_77),
	.Q(orig[7]));
   DFFQX1 \orig_reg[6]  (.CK(clk),
	.D(n_78),
	.Q(orig[6]));
   NAND2XL g4167__2346 (.A(n_72),
	.B(count[4]),
	.Y(n_87));
   OAI211XL g4168__1666 (.A0(count[3]),
	.A1(n_50),
	.B0(n_72),
	.C0(n_70),
	.Y(n_86));
   SDFFQX1 \nextstate_reg[1]  (.CK(clk),
	.D(nextstate[1]),
	.Q(nextstate[1]),
	.SE(n_68),
	.SI(n_29));
   SDFFQX1 element_done_reg (.CK(clk),
	.D(element_done),
	.Q(element_done),
	.SE(n_63),
	.SI(n_46));
   SDFFQX1 \nextstate_reg[0]  (.CK(clk),
	.D(nextstate[0]),
	.Q(nextstate[0]),
	.SE(n_68),
	.SI(n_24));
   OAI2BB1XL g4172__7410 (.A0N(n_71),
	.A1N(count[1]),
	.B0(n_74),
	.Y(n_85));
   OAI2BB1XL g4173__6417 (.A0N(orig[0]),
	.A1N(n_67),
	.B0(n_4),
	.Y(n_84));
   OAI2BB1XL g4174__5477 (.A0N(orig[1]),
	.A1N(n_67),
	.B0(n_4),
	.Y(n_83));
   SDFFQXL re_reg (.CK(clk),
	.D(re),
	.Q(re),
	.SE(n_62),
	.SI(n_55));
   SDFFQXL we_reg (.CK(clk),
	.D(we),
	.Q(we),
	.SE(n_62),
	.SI(n_53));
   SDFFQXL \datain_reg[0]  (.CK(clk),
	.D(datain[0]),
	.Q(datain[0]),
	.SE(n_3),
	.SI(n_25));
   OAI211XL g4178__2398 (.A0(n_59),
	.A1(n_22),
	.B0(n_69),
	.C0(n_40),
	.Y(n_82));
   OAI2BB1XL g4179__5107 (.A0N(orig[3]),
	.A1N(n_67),
	.B0(n_4),
	.Y(n_81));
   OAI2BB1XL g4180__6260 (.A0N(orig[5]),
	.A1N(n_67),
	.B0(n_4),
	.Y(n_80));
   OAI2BB1XL g4181__4319 (.A0N(orig[4]),
	.A1N(n_67),
	.B0(n_4),
	.Y(n_79));
   OAI2BB1XL g4182__8428 (.A0N(orig[6]),
	.A1N(n_67),
	.B0(n_4),
	.Y(n_78));
   OAI2BB1XL g4183__5526 (.A0N(orig[7]),
	.A1N(n_67),
	.B0(n_4),
	.Y(n_77));
   OAI2BB1XL g4184__6783 (.A0N(orig[2]),
	.A1N(n_67),
	.B0(n_4),
	.Y(n_76));
   DFFSHQX1 Test_reg (.CK(clk),
	.D(n_66),
	.Q(Test),
	.SN(n_5));
   OAI211XL g4187__3680 (.A0(count[0]),
	.A1(count[1]),
	.B0(n_21),
	.C0(n_70),
	.Y(n_74));
   NAND2XL g4188__1617 (.A(n_65),
	.B(n_40),
	.Y(n_73));
   NOR2XL g4189__2802 (.A(n_64),
	.B(n_15),
	.Y(n_75));
   CLKINVX1 g4190 (.A(n_71),
	.Y(n_70));
   NAND2XL g4191__1705 (.A(n_56),
	.B(n_57),
	.Y(n_69));
   SDFFRHQX1 \element_operation_reg[2]  (.CK(clk),
	.D(n_1),
	.Q(element_operation[2]),
	.RN(n_5),
	.SE(n_49),
	.SI(element_operation[2]));
   SDFFRHQX1 \element_operation_reg[0]  (.CK(clk),
	.D(n_6),
	.Q(element_operation[0]),
	.RN(n_5),
	.SE(n_49),
	.SI(element_operation[0]));
   SDFFRHQX1 \element_operation_reg[1]  (.CK(clk),
	.D(n_28),
	.Q(element_operation[1]),
	.RN(n_5),
	.SE(n_49),
	.SI(element_operation[1]));
   NAND2XL g4195__5122 (.A(n_50),
	.B(count[3]),
	.Y(n_72));
   NAND2XL g4196__8246 (.A(n_58),
	.B(Test),
	.Y(n_71));
   OA21X1 g4198__7098 (.A0(n_54),
	.A1(n_26),
	.B0(Test),
	.Y(n_66));
   AOI22XL g4199__6131 (.A0(n_34),
	.A1(n_56),
	.B0(n_32),
	.B1(n_23),
	.Y(n_65));
   AOI211XL g4200__1881 (.A0(fresh_state),
	.A1(n_37),
	.B0(n_52),
	.C0(n_39),
	.Y(n_64));
   AOI21XL g4201__5115 (.A0(n_45),
	.A1(n_0),
	.B0(n_15),
	.Y(n_63));
   AOI211XL g4202__7482 (.A0(n_29),
	.A1(n_36),
	.B0(n_54),
	.C0(rst),
	.Y(n_68));
   OAI211XL g4203__4733 (.A0(fresh_state),
	.A1(n_48),
	.B0(n_19),
	.C0(n_14),
	.Y(n_67));
   AOI211XL g4204__6161 (.A0(element_operation[2]),
	.A1(n_24),
	.B0(n_41),
	.C0(n_18),
	.Y(n_61));
   AOI21X1 g4206__9315 (.A0(n_43),
	.A1(n_38),
	.B0(n_15),
	.Y(n_62));
   MXI2XL g4207__9945 (.A(n_22),
	.B(n_44),
	.S0(n_31),
	.Y(n_60));
   MXI2XL g4208__2883 (.A(n_10),
	.B(CA[3]),
	.S0(n_30),
	.Y(n_59));
   OAI21XL g4209__2346 (.A0(fresh_state),
	.A1(n_38),
	.B0(n_0),
	.Y(n_58));
   MXI2XL g4210__1666 (.A(n_10),
	.B(CA[3]),
	.S0(n_27),
	.Y(n_57));
   OAI21XL g4211__7410 (.A0(n_2),
	.A1(n_36),
	.B0(n_26),
	.Y(n_55));
   NOR2XL g4212__6417 (.A(n_44),
	.B(fresh_state),
	.Y(n_56));
   DFFSHQX1 fresh_state_reg (.CK(clk),
	.D(n_134),
	.Q(fresh_state),
	.SN(n_5));
   INVX1 g4215 (.A(n_0),
	.Y(n_52));
   AOI21XL g4216__5477 (.A0(n_21),
	.A1(n_12),
	.B0(n_50),
	.Y(n_51));
   NAND3XL g4217__2398 (.A(n_33),
	.B(n_8),
	.C(Test),
	.Y(n_54));
   OAI2BB1XL g4218__5107 (.A0N(n_37),
	.A1N(n_2),
	.B0(n_29),
	.Y(n_53));
   NAND2XL g4220__6260 (.A(n_35),
	.B(n_7),
	.Y(n_48));
   NOR2XL g4222__8428 (.A(n_21),
	.B(n_12),
	.Y(n_50));
   NAND2XL g4223__5526 (.A(n_37),
	.B(Test),
	.Y(n_49));
   INVX1 g4224 (.A(n_45),
	.Y(n_46));
   OAI21XL g4225__6783 (.A0(n_18),
	.A1(n_2),
	.B0(n_37),
	.Y(n_43));
   OAI21XL g4226__3680 (.A0(CA[0]),
	.A1(fresh_state),
	.B0(n_40),
	.Y(n_42));
   AOI21XL g4227__1617 (.A0(n_23),
	.A1(element_operation[1]),
	.B0(element_operation[2]),
	.Y(n_41));
   NAND4XL g4228__2802 (.A(n_6),
	.B(element_operation[2]),
	.C(element_operation[1]),
	.D(n_37),
	.Y(n_45));
   NOR2XL g4229__1705 (.A(n_39),
	.B(n_25),
	.Y(n_44));
   INVX1 g4230 (.A(n_39),
	.Y(n_38));
   CLKINVX1 g4231 (.A(n_37),
	.Y(n_36));
   OAI31XL g4232__5122 (.A0(n_6),
	.A1(element_operation[2]),
	.A2(element_operation[1]),
	.B0(state[1]),
	.Y(n_35));
   NAND2XL g4233__8246 (.A(n_23),
	.B(fresh_state),
	.Y(n_40));
   NAND2XL g4234__7098 (.A(n_29),
	.B(n_26),
	.Y(n_39));
   NAND2XL g4235__6131 (.A(n_24),
	.B(n_22),
	.Y(n_37));
   MXI2XL g4236__1881 (.A(CA[2]),
	.B(n_9),
	.S0(n_20),
	.Y(n_34));
   NOR4BXL g4237__5115 (.AN(count[4]),
	.B(count[1]),
	.C(count[2]),
	.D(count[3]),
	.Y(n_33));
   OAI21XL g4238__7482 (.A0(n_16),
	.A1(n_9),
	.B0(n_30),
	.Y(n_32));
   NOR3BXL g4240__4733 (.AN(n_20),
	.B(fresh_state),
	.C(n_16),
	.Y(n_31));
   NOR2BXL g4241__6161 (.AN(n_17),
	.B(n_18),
	.Y(n_28));
   NOR2XL g4242__9315 (.A(n_9),
	.B(n_20),
	.Y(n_27));
   NAND2XL g4243__9945 (.A(n_9),
	.B(n_16),
	.Y(n_30));
   NAND3XL g4244__2883 (.A(n_11),
	.B(n_7),
	.C(n_19),
	.Y(n_29));
   CLKINVX1 g4245 (.A(n_24),
	.Y(n_25));
   INVX1 g4246 (.A(n_22),
	.Y(n_23));
   NAND3XL g4247__2346 (.A(state[1]),
	.B(state[0]),
	.C(n_19),
	.Y(n_26));
   NAND3XL g4249__1666 (.A(n_11),
	.B(state[0]),
	.C(n_19),
	.Y(n_24));
   NAND3XL g4250__7410 (.A(n_7),
	.B(state[1]),
	.C(n_19),
	.Y(n_22));
   NAND2XL g4251__6417 (.A(count[1]),
	.B(count[0]),
	.Y(n_21));
   NAND2XL g4252__5477 (.A(CA[0]),
	.B(CA[1]),
	.Y(n_20));
   NOR2XL g4253__2398 (.A(state[2]),
	.B(state[3]),
	.Y(n_19));
   INVXL g4254 (.A(n_15),
	.Y(n_14));
   NOR2XL g4255__5107 (.A(element_operation[1]),
	.B(element_operation[0]),
	.Y(n_18));
   NAND2XL g4256__6260 (.A(element_operation[1]),
	.B(element_operation[0]),
	.Y(n_17));
   NOR2XL g4257__4319 (.A(CA[0]),
	.B(CA[1]),
	.Y(n_16));
   NAND2XL g4258__8428 (.A(n_5),
	.B(Test),
	.Y(n_15));
   INVX1 g4259 (.A(fresh_state),
	.Y(n_13));
   CLKINVX1 g4260 (.A(count[2]),
	.Y(n_12));
   CLKINVX1 g4261 (.A(state[1]),
	.Y(n_11));
   CLKINVX1 g4263 (.A(CA[3]),
	.Y(n_10));
   INVX1 g4264 (.A(CA[2]),
	.Y(n_9));
   INVX1 g4265 (.A(count[0]),
	.Y(n_8));
   INVX1 g4266 (.A(state[0]),
	.Y(n_7));
   INVX1 g4267 (.A(element_operation[0]),
	.Y(n_6));
   INVX1 g4270 (.A(rst),
	.Y(n_5));
   NAND2BX1 g2__5526 (.AN(n_67),
	.B(n_61),
	.Y(n_4));
   NOR2BX1 g4271__6783 (.AN(n_53),
	.B(n_15),
	.Y(n_3));
   NOR3BX1 g4272__3680 (.AN(element_operation[1]),
	.B(element_operation[2]),
	.C(element_operation[0]),
	.Y(n_2));
   XNOR2XL g4273__1617 (.A(element_operation[2]),
	.B(n_17),
	.Y(n_1));
   NAND3BX1 g4274__2802 (.AN(fresh_state),
	.B(n_37),
	.C(element_done),
	.Y(n_0));
   BUFX20 g4275 (.A(1'b0),
	.Y(state[3]));
   BUFX20 g4276 (.A(1'b0),
	.Y(state[2]));
   AOI21X1 g2 (.A0(n_19),
	.A1(Test),
	.B0(n_13),
	.Y(n_134));
endmodule

